### ISSUE TITLE
Målgruppsanalys

### ISSUE THREAD

**Issue by itggot-adam-rohdell** [itggot-adam-rohdell/Slutprojekt#1]
Målgruppsanalys:
Kundens mål är att göra det så lätt som möjligt att hjälpa många elever med tekniska problem som t.ex. deras datorer eller annan hårdvara, ev. mjukvara.

Målgrupp:
ITG - Helpdesk riktar sig mot elever på IT-gymnasiet, både elever som är kunniga inom IT såväl som alla andra elever som helt enkelt har problem med sin hård- eller mjukvara. Den riktar sig mot de som behöver hjälp med sina datorer. Dessutom är den riktad till IT-ansvarig, vaktmästare såväl som olika typer av lärare.

**Comment by josefandersson** [comment]
I r8 8/8, gj m8
